POST http://localhost:3002/api/forumpost/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vZCIsImR1ZGVpZCI6MSwicm9sZWlkIjoyLCJpYXQiOjE1MjcwNzczODB9.71QbauIIrxPSUvxR3kXFCPJjwAOAy6KcTad14Yb26pc
Content-Type: application/json

{
    "title":"post",
    "content":"content",
    "categoryid":1
}